### ISSUE TITLE
Why is the class name is white? it should be #A6E22E

### ISSUE THREAD

**Issue by ajcastro** [trangcongthanh/flatland-monokai#1]
Help pls why is the class name becomes white. it should #A6E22E.

![image](https://user-images.githubusercontent.com/4918318/126731179-d48160be-c532-437f-b364-c1a502a4ba94.png)

**Comment by trangcongthanh** [comment]
I don't know. Maybe because the token name for it got changed. This extension not getting any update for 5 years :D

**Comment by ajcastro** [comment]
I think because of the language. Thanks for the response.

**Comment by trangcongthanh** [comment]
If I have some free time this weekend, I'll take a look at this issue. And I need to find which credential I used to publish this extension too 😢

**Comment by ajcastro** [comment]
Ok thanks. Btw the programming language in my example is PHP (laravel).

**Comment by ajcastro** [comment]
I managed to fix it by using textMateRules
```
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "entity.name.type.class.php",
                "settings": {
                    "foreground": "#A6E22E"
                }
            },
        ]
    },```

**Comment by trangcongthanh** [comment]
@ajcastro I was too busy last week. But I published a new version 0.1.3 included 2 tokens `name.type.class` for this issue and `name.function` for #2.

**Comment by ajcastro** [comment]
Thank you so much @trangcongthanh

**Comment by ajcastro** [comment]
@trangcongthanh if you have ko-fi links I am willing to donate some little amount to express my gratitude
