### ISSUE TITLE
Is it possible to change the function call text color without affecting text color of function declarations?

### ISSUE THREAD

**Issue by ajcastro** [trangcongthanh/flatland-monokai#2]
![image](https://user-images.githubusercontent.com/4918318/126778551-e01998d5-ac01-4175-a722-a86943ac170a.png)

In the image sample above. Is it possible to change the function calls but not the function declarations? 
so the `claim` method will still be yellowish and I like the method calls `query`, `where` and `update` to be whitish?

I tried adding the settings below but it all change function calls and also the function declaration. This is PHP file.
```
"editor.tokenColorCustomizations": {
        "[Flatland Monokai]": {
            "functions": "#F8F8F2"
        },```

**Comment by trangcongthanh** [comment]
Changed to #f8f8f2 in v0.1.3

**Comment by ajcastro** [comment]
Thank you so much @trangcongthanh
